# -*- coding: utf-8 -*-
"""Calc_idade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVnonYvPioSF4pGVpOnJRRqqFR2r1ULa
"""

def obter_nome():
    nome = input("Digite seu nome completo: ")
    return nome

def obter_ano_nascimento():
    while True:
        try:
            ano = int(input("Digite seu ano de nascimento (entre 1922 e 2021): "))
            if 1922 <= ano <= 2021:
                return ano
            else:
                print("Ano inválido. Por favor, digite um ano entre 1922 e 2021.")
        except ValueError:
            print("Entrada inválida. Por favor, digite um número.")

def calcular_idade(ano_nascimento, ano_atual):
    return ano_atual - ano_nascimento

def main():
    ano_atual = 2024
    nome = obter_nome()
    ano_nascimento = obter_ano_nascimento()
    idade = calcular_idade(ano_nascimento, ano_atual)
    print(f"{nome}, você completou ou completará {idade} anos em {ano_atual}.")

if __name__ == "__main__":
    main()