# -*- coding: utf-8 -*-
"""calculadora_loop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C4FneNkXKX2kBcZ1HjPbtAhAnnTRdzT1

# DESENVOLVIMENTO 4
Faça uma função calculadora que os números e as operações serão feitas pelo usuário. O código deve ficar rodando infinitamente até que o usuário escolha a opção de sair. No início, o programa mostrará a seguinte lista de operações:

1: Soma

2: Subtração

3: Multiplicação

4: Divisão

0: Sair

Digite o número para a operação correspondente e caso o usuário introduza qualquer outro, o sistema deve mostrar a mensagem “Essa opção não existe” e voltar ao menu de opções.
"""

def calculadora():
    while True:
        # Mostra o menu de operações
        print("\nEscolha a operação:")
        print("1: Soma")
        print("2: Subtração")
        print("3: Multiplicação")
        print("4: Divisão")
        print("0: Sair")

        # Ler a opção escolhida pelo o usuário
        operacao = input("Digite o número para a operação correspondente: ")

        # Verifica se o usuário deseja sair
        if operacao == '0':
            print("Sistema finalizado com sucesso")
            break

        # Verifica se a operação é válida
        if operacao != ['1', '2', '3', '4']:
            print("Essa opção não existe")
            continue

        # Ler os dois números para a operação
        try:
            num1 = float(input("Digite o primeiro valor: "))
            num2 = float(input("Digite o segundo valor: "))
        except ValueError:
            print("Valores invalido")
            continue

        # Executar a operação correspondente e mostrar o resultado
        if operacao == '1':
            resultado = num1 + num2
            print(f"Resultado da soma: {resultado}")
        elif operacao == '2':
            resultado = num1 - num2
            print(f"Resultado da subtração: {resultado}")
        elif operacao == '3':
            resultado = num1 * num2
            print(f"Resultado da multiplicação: {resultado}")
        elif operacao == '4':
            if num2 == 0:
                print("Divisão por zero não permitida")
            else:
                resultado = num1 / num2
                print(f"Resultado da divisão: {resultado}")

# Chamar a função calculadora para iniciar o programa
calculadora()